"""The group machinery must answer or refuse, and never report a number near a cap.

`order()` returned 1000 for S_7, whose order is 5040, and 1001 for S_8, whose
order is 40320 -- the second being neither the order nor the budget, because the
budget was tested before processing a queue entry that then added several
elements. `orbit()` inherited the same cap and returned half of a 2000-point
orbit. `Permutation` accepted maps that are not bijections.

These tests check the group laws directly rather than trusting the enumeration:
closure under composition, presence of inverses, and that orbits partition the
points. A truncated closure fails all three, which is how a budget that
truncates is caught without knowing the right answer in advance.

The `negative_control` tests reproduce the replaced logic, so the defects stay
legible once the source no longer exhibits them.
"""

from __future__ import annotations

import pytest

from grounded_hypercalculi.hyper_calculus import (
    DerivationOperator,
    Permutation,
    PermutationGroup,
    commutator_bracket,
)

IDENTITY = Permutation({})


def cycle(n: int) -> Permutation:
    """The n-cycle (0 1 2 ... n-1)."""
    return Permutation({i: (i + 1) % n for i in range(n)})


def transposition(a: int, b: int) -> Permutation:
    return Permutation({a: b, b: a})


def symmetric(n: int) -> PermutationGroup:
    """S_n, generated by an n-cycle and a transposition."""
    return PermutationGroup([cycle(n), transposition(0, 1)])


# ============================================================================
# 1. order() is the order, or it is a refusal
# ============================================================================


@pytest.mark.parametrize(
    "n, factorial",
    [(3, 6), (4, 24), (5, 120), (6, 720), (7, 5040)],
)
def test_the_order_of_a_symmetric_group_is_n_factorial(n: int, factorial: int) -> None:
    assert symmetric(n).order() == factorial


def test_the_order_of_a_cyclic_group_is_its_length() -> None:
    # 1200 elements, past the old cap of 1000, and previously reported as 1000.
    # Kept at 1200 rather than larger because composing two permutations rebuilds
    # and rehashes a dict the size of their support, so enumerating C_n costs
    # O(n^2) -- C_2000 takes 2.4s where C_1200 takes 0.5s.
    assert PermutationGroup([cycle(1200)]).order() == 1200


def test_a_group_past_the_budget_is_refused_not_approximated() -> None:
    # S_8 has 40320 elements. The old code answered 1001.
    with pytest.raises(ValueError, match="more than 10000 elements"):
        symmetric(8).order()


def test_the_budget_can_be_raised_to_get_the_true_order() -> None:
    assert len(symmetric(8).generate(max_elements=50_000)) == 40_320


def test_a_budget_below_one_is_refused() -> None:
    with pytest.raises(ValueError, match="at least 1"):
        symmetric(3).generate(max_elements=0)


def test_negative_control_the_truncating_loop_returns_neither_order_nor_cap() -> None:
    # The replaced loop, reproduced exactly. It tested the budget once per queue
    # entry rather than once per insertion, so it overshot.
    def legacy_generate(generators, max_elements=1000):
        elements = {IDENTITY}
        queue = [IDENTITY]
        while queue and len(elements) < max_elements:
            curr = queue.pop(0)
            for g in generators:
                comp = curr * g
                if comp not in elements:
                    elements.add(comp)
                    queue.append(comp)
        return elements

    s7 = legacy_generate([cycle(7), transposition(0, 1)])
    s8 = legacy_generate([cycle(8), transposition(0, 1)])
    assert len(s7) == 1000, "S_7 has 5040 elements"
    assert len(s8) == 1001, "S_8 has 40320 elements, and 1001 is not even the cap"


# ============================================================================
# 2. What comes back is a group
# ============================================================================


def test_the_closure_is_closed_under_composition() -> None:
    elements = symmetric(5).generate()
    assert all(a * b in elements for a in elements for b in elements)


def test_every_element_of_the_closure_has_its_inverse_in_the_closure() -> None:
    elements = symmetric(5).generate()
    assert all(any(a * b == IDENTITY for b in elements) for a in elements)


def test_the_identity_is_in_the_closure() -> None:
    assert IDENTITY in symmetric(5).generate()


def test_negative_control_the_truncated_set_is_not_a_group() -> None:
    # The three properties above are what a partial closure fails, and they are
    # checkable without knowing the true order. That is the point of testing
    # them rather than the count alone.
    def legacy_generate(generators, max_elements=1000):
        elements = {IDENTITY}
        queue = [IDENTITY]
        while queue and len(elements) < max_elements:
            curr = queue.pop(0)
            for g in generators:
                comp = curr * g
                if comp not in elements:
                    elements.add(comp)
                    queue.append(comp)
        return elements

    truncated = legacy_generate([cycle(7), transposition(0, 1)])
    sample = sorted(truncated, key=lambda p: sorted(p.mapping.items()))[:40]

    unclosed = [(a, b) for a in sample for b in sample if a * b not in truncated]
    assert unclosed, "the truncated set was not closed under composition"

    without_inverse = [
        a for a in sample if not any(a * b == IDENTITY for b in truncated)
    ]
    assert without_inverse, "members of the truncated set had no inverse present"


# ============================================================================
# 3. Orbits
# ============================================================================


def test_the_orbit_of_a_point_under_a_cycle_is_every_point_of_the_cycle() -> None:
    assert PermutationGroup([cycle(7)]).orbit(0) == set(range(7))


def test_a_long_orbit_is_not_truncated_by_the_group_budget() -> None:
    # 2000 points; previously 1000 of them came back, silently.
    assert PermutationGroup([cycle(2000)]).orbit(0) == set(range(2000))


def test_an_orbit_is_available_for_a_group_far_too_large_to_enumerate() -> None:
    # S_20 has 20! elements -- about 2.4e18, which will not be enumerated under
    # any budget. Its orbit of 0 has twenty points and costs nothing. Computing
    # the orbit through the closure threw that gap away.
    group = symmetric(20)
    assert group.orbit(0) == set(range(20))
    with pytest.raises(ValueError):
        group.order()


def test_orbits_partition_the_points() -> None:
    # Distinct orbits are disjoint and cover everything. The non-bijection
    # Permutation used to accept produced overlapping orbits that were not equal.
    group = symmetric(5)
    points = range(8)
    orbits = {frozenset(group.orbit(x)) for x in points}
    assert sorted(sorted(o) for o in orbits) == [[0, 1, 2, 3, 4], [5], [6], [7]]
    for a in orbits:
        for b in orbits:
            assert a == b or not (a & b)


def test_a_point_is_always_in_its_own_orbit() -> None:
    assert 99 in PermutationGroup([cycle(5)]).orbit(99)
    assert PermutationGroup([]).orbit(3) == {3}


# ============================================================================
# 4. A Permutation must permute
# ============================================================================


def test_a_non_injective_map_is_refused() -> None:
    # 1 and 3 both land on 2, and nothing lands on 1 or 3.
    with pytest.raises(ValueError, match="not injective"):
        Permutation({1: 2, 3: 2})


def test_a_map_that_moves_a_point_without_covering_it_is_refused() -> None:
    # 1 -> 2 alone also sends 2 -> 2, so 2 has two preimages.
    with pytest.raises(ValueError, match="does not permute its own support"):
        Permutation({1: 2})


def test_a_cycle_with_one_entry_too_many_is_refused() -> None:
    with pytest.raises(ValueError, match="not injective"):
        Permutation({0: 1, 1: 2, 2: 0, 3: 0})


def test_genuine_permutations_are_unaffected() -> None:
    assert Permutation({1: 2, 2: 1}).apply(1) == 2
    assert Permutation({1: 1, 2: 2}) == IDENTITY
    assert hash(Permutation({1: 1})) == hash(IDENTITY)
    assert cycle(6).apply(5) == 0


def test_composition_of_permutations_is_a_permutation() -> None:
    # __mul__ builds a new Permutation, so validation runs on every product. If
    # composition could produce a non-bijection this would raise.
    elements = symmetric(5).generate()
    for a in list(elements)[:20]:
        for b in list(elements)[:20]:
            product = a * b
            assert set(product.mapping) == set(product.mapping.values())


def test_negative_control_the_old_canonicalization_accepted_a_non_bijection() -> None:
    # The replaced __post_init__ dropped fixed points and stopped there.
    raw = {1: 2, 3: 2}
    cleaned = {k: v for k, v in raw.items() if k != v}
    assert cleaned == raw, "nothing was dropped, and nothing else was checked"
    images = list(cleaned.values())
    assert len(set(images)) != len(images), "which the check now added catches"


# ============================================================================
# 5. Derivations and the Lie bracket -- this part was already right
# ============================================================================

_H = 1e-5


def _scaled_derivative(coefficient):
    """f -> coefficient(x) * f'(x), a derivation for any smooth coefficient."""
    return lambda f: (lambda x: coefficient(x) * (f(x + _H) - f(x - _H)) / (2 * _H))


D_DX = DerivationOperator("d/dx", _scaled_derivative(lambda x: 1.0))
X_D_DX = DerivationOperator("x d/dx", _scaled_derivative(lambda x: x))


def _f(x: float) -> float:
    return x ** 2 + 1.0


def _g(x: float) -> float:
    return 3.0 * x + 2.0


def test_the_generators_satisfy_leibniz() -> None:
    assert D_DX.leibniz_check(_f, _g, 1.3) is True
    assert X_D_DX.leibniz_check(_f, _g, 1.3) is True


def test_the_bracket_of_two_derivations_is_itself_a_derivation() -> None:
    # The Lie algebra fact: derivations are closed under the commutator, even
    # though general linear operators are not.
    bracket = commutator_bracket(D_DX, X_D_DX)
    assert bracket.leibniz_check(_f, _g, 1.3) is True


def test_the_bracket_is_antisymmetric() -> None:
    forward = commutator_bracket(D_DX, X_D_DX).apply(_f)(1.3)
    reversed_ = commutator_bracket(X_D_DX, D_DX).apply(_f)(1.3)
    assert forward == pytest.approx(-reversed_, abs=1e-9)


def test_the_bracket_of_an_operator_with_itself_vanishes() -> None:
    assert commutator_bracket(D_DX, D_DX).apply(_f)(1.3) == pytest.approx(0.0, abs=1e-9)


def test_leibniz_check_says_no_when_the_rule_fails() -> None:
    # Squaring is not a derivation: D(fg) = (fg)^2, not f^2 g + f g^2.
    squaring = DerivationOperator("f -> f^2", lambda f: (lambda x: f(x) ** 2))
    assert squaring.leibniz_check(_f, _g, 1.3) is False


def test_the_identity_operator_is_not_a_derivation() -> None:
    # D(fg) = fg, but D(f)g + fD(g) = 2fg. Equal only where fg is zero.
    identity_op = DerivationOperator("f -> f", lambda f: f)
    assert identity_op.leibniz_check(_f, _g, 1.3) is False


# ============================================================================
# 6. contains_identity reports a definition
# ============================================================================


def test_contains_identity_is_true_and_asks_nothing() -> None:
    # Retained public API. It cannot return False, which is why the closure is
    # checked for the identity separately above.
    assert PermutationGroup([]).contains_identity() is True
    assert symmetric(20).contains_identity() is True
