import pytest
from grounded_hypercalculi.hyper_calculus import (
    DerivationOperator,
    Permutation,
    PermutationGroup,
    commutator_bracket,
)


def test_permutations():
    p1 = Permutation({1: 2, 2: 1})
    assert p1.apply(1) == 2
    assert p1.apply(2) == 1
    assert p1.apply(3) == 3

    # Composition
    p2 = Permutation({2: 3, 3: 2})
    p_comp = p2 * p1
    assert p_comp.apply(1) == 3

    # Hashability and set membership
    s = {p1, p2}
    assert p1 in s
    assert hash(p1) == hash(Permutation({1: 2, 2: 1}))

    # Canonical identity equality
    assert Permutation({1: 1, 2: 2}) == Permutation({})
    assert hash(Permutation({1: 1})) == hash(Permutation({}))


def test_permutation_group_closure_and_orbits():
    # S3 generated by (1 2) and (2 3)
    p1 = Permutation({1: 2, 2: 1})
    p2 = Permutation({2: 3, 3: 2})
    group = PermutationGroup(generators=[p1, p2])

    assert group.contains_identity()
    elements = group.generate()
    # S_3 has 6 elements: e, (1 2), (2 3), (1 3), (1 2 3), (1 3 2)
    assert len(elements) == 6
    assert group.order() == 6

    # Orbit of 1 under S_3 is {1, 2, 3}
    assert group.orbit(1) == {1, 2, 3}



def test_derivation_and_leibniz_rule():
    # Numerical derivative operator
    d_op = lambda f: (lambda x: (f(x + 1e-6) - f(x - 1e-6)) / 2e-6)
    D = DerivationOperator("D", d_op)

    f = lambda x: x ** 2
    g = lambda x: 3 * x + 1
    assert D.leibniz_check(f, g, x=2.0)


def test_lie_commutator_bracket():
    # D1 = d/dx, D2 = x d/dx
    D1 = DerivationOperator("D1", lambda f: (lambda x: (f(x + 1e-5) - f(x - 1e-5)) / 2e-5))
    D2 = DerivationOperator("D2", lambda f: (lambda x: x * (f(x + 1e-5) - f(x - 1e-5)) / 2e-5))

    bracket = commutator_bracket(D1, D2)
    test_func = lambda x: x ** 3
    # [D1, D2] f = D1(x f') - D2(f') = f' + x f'' - x f'' = f'
    # At x = 2, f'(2) = 12
    val = bracket.apply(test_func)(2.0)
    assert abs(val - 12.0) < 0.1
