"""Hyper-Calculus: automorphism groups, semantic symmetries, Lie derivations, and Noether invariants."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Sequence, Set, Tuple


@dataclass(frozen=True)
class Permutation:
    """A permutation over an integer or string coordinate set."""
    mapping: Dict[Any, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        # Canonicalize: drop non-trivial identity mappings k == v
        cleaned = {k: v for k, v in self.mapping.items() if k != v}
        object.__setattr__(self, "mapping", cleaned)

    def apply(self, elem: Any) -> Any:
        return self.mapping.get(elem, elem)

    def __hash__(self) -> int:
        return hash(frozenset(self.mapping.items()))

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Permutation):
            return False
        return self.mapping == other.mapping

    def __mul__(self, other: Permutation) -> Permutation:
        """Composition of permutations: (p1 * p2)(x) = p1(p2(x))."""
        all_keys = set(self.mapping.keys()) | set(other.mapping.keys())
        comp: Dict[Any, Any] = {}
        for k in all_keys:
            val = self.apply(other.apply(k))
            if val != k:
                comp[k] = val
        return Permutation(comp)


@dataclass
class PermutationGroup:
    """A permutation group generated by a set of permutations."""
    generators: List[Permutation] = field(default_factory=list)

    def contains_identity(self) -> bool:
        return True

    def generate(self, max_elements: int = 1000) -> Set[Permutation]:
        """Compute the finite group closure generated by the generators."""
        identity = Permutation({})
        elements: Set[Permutation] = {identity}
        queue: List[Permutation] = [identity]
        while queue and len(elements) < max_elements:
            curr = queue.pop(0)
            for g in self.generators:
                comp = curr * g
                if comp not in elements:
                    elements.add(comp)
                    queue.append(comp)
        return elements

    def order(self) -> int:
        """Return the order of the group (number of elements in closure)."""
        return len(self.generate())

    def orbit(self, elem: Any) -> Set[Any]:
        """Compute the orbit of an element under the group action."""
        return {p.apply(elem) for p in self.generate()}



@dataclass(frozen=True)
class DerivationOperator:
    """A linear derivation operator D on a functional space satisfying the Leibniz rule."""
    name: str
    d_op: Callable[[Callable[[float], float]], Callable[[float], float]]

    def apply(self, f: Callable[[float], float]) -> Callable[[float], float]:
        return self.d_op(f)

    def leibniz_check(
        self,
        f: Callable[[float], float],
        g: Callable[[float], float],
        x: float,
        tol: float = 1e-4,
    ) -> bool:
        """Verify the Leibniz product rule: D(fg) = D(f)g + fD(g) at point x."""
        fg = lambda t: f(t) * g(t)
        df_g_plus_f_dg = self.apply(f)(x) * g(x) + f(x) * self.apply(g)(x)
        d_fg = self.apply(fg)(x)
        return abs(d_fg - df_g_plus_f_dg) < tol


def commutator_bracket(
    d1: DerivationOperator,
    d2: DerivationOperator,
) -> DerivationOperator:
    """Lie commutator bracket [D1, D2] = D1 o D2 - D2 o D1."""
    def bracket_op(f: Callable[[float], float]) -> Callable[[float], float]:
        d1_d2 = d1.apply(d2.apply(f))
        d2_d1 = d2.apply(d1.apply(f))
        return lambda x: d1_d2(x) - d2_d1(x)

    return DerivationOperator(f"[{d1.name},{d2.name}]", bracket_op)
