"""Hyper-Calculus: permutation groups, derivation operators, and Lie brackets.

What is here: ``Permutation`` and ``PermutationGroup`` (closure, order, orbits
under a group action), ``DerivationOperator`` with a pointwise Leibniz check,
and ``commutator_bracket``, whose bracket of two derivations is itself a
derivation -- the Lie algebra fact, and it is tested.

What is *not* here, despite earlier wording: there is no Noether invariant, and
nothing computes an automorphism group. A ``PermutationGroup`` is generated from
permutations the caller supplies; it is not ``Aut(G)`` of any structure, and the
module never asks what the permutations are symmetries *of*. Conserved
quantities under a symmetry are exactly what a Noether statement is about, so
the name claimed the part that is missing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional, Sequence, Set, Tuple


@dataclass(frozen=True)
class Permutation:
    """A permutation over an integer or string coordinate set."""
    mapping: Dict[Any, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        # Canonicalize by dropping fixed points, so that {1: 1} and {} are the
        # same permutation and hash alike.
        cleaned = {k: v for k, v in self.mapping.items() if k != v}

        # What remains must permute its own support: the moved points and their
        # images are the same set, each hit once. Without this check
        # Permutation({1: 2, 3: 2}) constructs -- 1 and 3 both land on 2, and
        # nothing lands on 1 or 3. It is not invertible, so it generates no
        # group, and the orbits it produced overlapped without being equal,
        # which is impossible for a group action.
        images = list(cleaned.values())
        if len(set(images)) != len(images):
            duplicated = sorted(
                (str(v) for v in images if images.count(v) > 1), key=str
            )
            raise ValueError(
                f"mapping is not injective: {duplicated[0]} is the image of more "
                f"than one point, so this is not a permutation"
            )
        if set(cleaned) != set(images):
            unmatched = sorted(
                (str(x) for x in set(cleaned) ^ set(images)), key=str
            )
            raise ValueError(
                f"mapping does not permute its own support: {', '.join(unmatched)} "
                f"appears on only one side. A point that is moved must also be "
                f"the image of some point; add the missing entries or drop the "
                f"partial ones"
            )

        object.__setattr__(self, "mapping", cleaned)

    def apply(self, elem: Any) -> Any:
        return self.mapping.get(elem, elem)

    def __hash__(self) -> int:
        return hash(frozenset(self.mapping.items()))

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, Permutation):
            return False
        return self.mapping == other.mapping

    def __mul__(self, other: Permutation) -> Permutation:
        """Composition of permutations: (p1 * p2)(x) = p1(p2(x))."""
        all_keys = set(self.mapping.keys()) | set(other.mapping.keys())
        comp: Dict[Any, Any] = {}
        for k in all_keys:
            val = self.apply(other.apply(k))
            if val != k:
                comp[k] = val
        return Permutation(comp)


# Ceiling on the number of elements PermutationGroup.generate will enumerate.
# Permutation groups grow factorially -- S_8 already has 40320 elements -- so a
# budget is needed. Past it the operator refuses rather than returning a
# partial closure, which is not a group.
_DEFAULT_GROUP_BUDGET = 10_000


@dataclass
class PermutationGroup:
    """A permutation group generated by a set of permutations."""
    generators: List[Permutation] = field(default_factory=list)

    def contains_identity(self) -> bool:
        """Always True. Every group contains the identity, by definition.

        This asks nothing of the generators and cannot return False, so it
        reports a definitional fact rather than checking one. It is kept because
        it is public API; a caller wanting evidence that the closure is
        well-formed should take ``generate()`` and inspect it.
        """
        return True

    def generate(self, max_elements: int = _DEFAULT_GROUP_BUDGET) -> Set[Permutation]:
        """The group generated by ``generators``, or a refusal.

        Closure under right multiplication by the generators, starting from the
        identity. Inverses need not be supplied: in a finite permutation group
        every element's inverse is one of its own positive powers, so the
        products of generators already form the whole subgroup.

        The enumeration previously stopped at the budget and returned what it
        had. That set is not a group -- past the cap it was not closed under
        composition, and most of its members had no inverse in it -- so it is
        now refused instead. A partial closure answers no question about the
        group that a caller would ask a closure for.

        Raises:
            ValueError: if the group has more than ``max_elements`` elements.
                Raise the budget to spend the memory, or ask ``orbit`` directly
                if the orbit rather than the group is what is wanted.
        """
        if max_elements < 1:
            raise ValueError("max_elements must be at least 1")
        identity = Permutation({})
        elements: Set[Permutation] = {identity}
        queue: List[Permutation] = [identity]
        while queue:
            curr = queue.pop()
            for g in self.generators:
                comp = curr * g
                if comp in elements:
                    continue
                if len(elements) >= max_elements:
                    raise ValueError(
                        f"the group generated by these {len(self.generators)} "
                        f"generators has more than {max_elements} elements; "
                        f"raise max_elements to enumerate it. Permutation groups "
                        f"grow factorially, so a budget that fits one generating "
                        f"set will not fit a slightly larger one"
                    )
                elements.add(comp)
                queue.append(comp)
        return elements

    def order(self) -> int:
        """The number of elements in the group.

        Enumerates the closure, so it refuses for groups past the default
        budget rather than reporting a number near it. It previously returned
        1000 for S_7 (order 5040) and 1001 for S_8 (order 40320) -- the second
        being neither the order nor the budget, since the budget was tested
        before processing a queue entry that then added several elements.
        """
        return len(self.generate())

    def orbit(self, elem: Any) -> Set[Any]:
        """The orbit of ``elem``: every point reachable from it under the group.

        Closes ``elem`` under the generators directly instead of enumerating the
        group, which is both correct and far cheaper. An orbit is bounded by the
        points the generators move, not by the group's order, and the two are
        not close: the orbit of 0 under S_20 has 20 points while the group has
        20! of them.

        Enumerating the group to answer this also made the orbit inherit the
        group's budget. The orbit of 0 under a single 2000-cycle came back with
        1000 of its 2000 points, and nothing in the result said so.
        """
        seen: Set[Any] = {elem}
        queue: List[Any] = [elem]
        while queue:
            point = queue.pop()
            for g in self.generators:
                image = g.apply(point)
                if image not in seen:
                    seen.add(image)
                    queue.append(image)
        return seen



@dataclass(frozen=True)
class DerivationOperator:
    """A linear derivation operator D on a functional space satisfying the Leibniz rule."""
    name: str
    d_op: Callable[[Callable[[float], float]], Callable[[float], float]]

    def apply(self, f: Callable[[float], float]) -> Callable[[float], float]:
        return self.d_op(f)

    def leibniz_check(
        self,
        f: Callable[[float], float],
        g: Callable[[float], float],
        x: float,
        tol: float = 1e-4,
    ) -> bool:
        """Verify the Leibniz product rule: D(fg) = D(f)g + fD(g) at point x."""
        fg = lambda t: f(t) * g(t)
        df_g_plus_f_dg = self.apply(f)(x) * g(x) + f(x) * self.apply(g)(x)
        d_fg = self.apply(fg)(x)
        return abs(d_fg - df_g_plus_f_dg) < tol


def commutator_bracket(
    d1: DerivationOperator,
    d2: DerivationOperator,
) -> DerivationOperator:
    """Lie commutator bracket [D1, D2] = D1 o D2 - D2 o D1."""
    def bracket_op(f: Callable[[float], float]) -> Callable[[float], float]:
        d1_d2 = d1.apply(d2.apply(f))
        d2_d1 = d2.apply(d1.apply(f))
        return lambda x: d1_d2(x) - d2_d1(x)

    return DerivationOperator(f"[{d1.name},{d2.name}]", bracket_op)
